# Copied from https://stackoverflow.com/questions/35445186/can-github-automatically-merge-branches
# I'm using a bare git repo, to keep my home folder clean I'm pushing everything to dev branch and having this merge it into main
name: Automerge

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  MY_REPO: https://stormytuna:${{secrets.GITHUB_TOKEN}}@github.com/stormytuna/Dotfiles.git
  MAIN_BRANCH: main
  DEV_BRANCH: dev

jobs:
  merge:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Merge with main
        run: |
          git clone ${{env.MY_REPO}} -b ${{env.MAIN_BRANCH}} tmp
          cd tmp
          git config user.name "Automerge Bot"
          git config user.email "bot@example.com"
          git config pull.rebase false
          git pull ${{env.MY_REPO}} ${{env.DEV_BRANCH}}
          git push
